experiment_name: "dynamic_concept_with_novelty_kaggle"
seed: 42

dataset:
  source: mcts_trajectories
  board_size: 8  # Must be 8 for Kaggle dataset!
  n_pairs: 30
  max_attempts: 500
  n_sims: 200
  depth: 5
  min_value_gap: 0.15
  min_visit_ratio: 1.10
  checkpoint_path: "models/alphazero-othello-8/"
  name: "alphazero-othello-8"

model:
  source: "file"
  board_size: 8  # Must match dataset!
  name: "alphazero-othello-8"
  checkpoint_path: "models/alphazero-othello-8/"

hooks:
  layers:
    - {name: "conv1"}
    - {name: "conv2"}
    - {name: "conv3"}
    - {name: "conv4"}
    - {name: "fc1"}
    - {name: "fc2"}

optimization:
  method: dynamic_convex
  batch_size: 10
  margin: 0.0

evaluation:
  test_split: 0.2
  runs:
    - {name: trajectory_constraint_satisfaction, margin: 0.0}
    - {name: trajectory_pair_accuracy}
    - {name: sparsity, threshold: 1.0e-6}

# Novelty filtering configuration
novelty_filtering:
  enabled: true
  human_source: "kaggle_othello_games"  # Use Kaggle dataset
  az_source: "self_play"
  
  # For human games (Kaggle)
  n_samples: 10  # Target number of positions (paper uses 17184)
  min_move_number: 8   # Skip opening (moves 1-7)
  max_move_number: 50  # Skip endgame
  
  # For AZ games  
  n_games: 100  # Number of self-play games to generate